server:
  port: 8081
spring:
  application:
    name: OrderDDD
  datasource:
    url: jdbc:postgresql://101.43.97.81:5432/order_ddd
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: 101.43.97.81
    port: 5672
    username: myuser
    password: mypassword
nacos:
  discovery:
    server-addr: 154.21.201.99:8848
  config:
    data-id: orderDDD
    group: DEFAULT_GROUP
