server:
  port: 8081
spring:
  application:
    name: OrderDDD
  datasource:
    url: jdbc:postgresql://101.43.97.81:5432/order_ddd
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: 101.43.97.81
    port: 5672
    username: myuser
    password: mypassword
    publisher-confirm-type: correlated
    publisher-returns: true
    # 消费者配置
    listener:
      simple:
        # 设置预取数量为5
        prefetch: 5
        # 手动确认模式
        acknowledge-mode: manual
        # 每个队列启动的消费者数量
        concurrency: 1
        # 每个队列最大的消费者数量
        max-concurrency: 5
nacos:
  discovery:
    server-addr: 154.21.201.99:8848
  config:
    data-id: orderDDD
    group: DEFAULT_GROUP
